### ISSUE TITLE
Enhancement with hchart %>% hc_xAxis(type = "logarithmic")

### ISSUE THREAD

**Issue by drodtp** [jbkunst/highcharter#102]
The bars overlap.
Also doesn't handle well values below 1.

Here is a simple code to reproduce the problem
`hchart(10**rnorm(1000)) %>% hc_xAxis(type = "logarithmic")`

**Comment by jbkunst** [comment]
Hi @drodtp 

Yep :pensive:, this is because the code made every "bar" by hand due highcharts don't support histograms natively. So we need to construct the chart bar by bar, calculating their widths previously (see `highcharter:::hchart.histogram`).

So this is not relly a bug but a missing feature :wink:.

I think there's no a quick solution but there's a quick hack if you want to chart some log values:

- Chart the log values
- Change the xAxis labels to the original scale
- Same in the tooltip

```
set.seed(1)

x <- 10**rnorm(1000)

summary(x)

hchart(x) 

hchart(x) %>% hc_xAxis(type = "logarithmic")


hchart(log(x)) %>% 
  hc_xAxis(
    labels = list(
      formatter = JS("function(){ return Math.round(100*Math.exp(this.value), 5)/100;}")  
      )
    ) %>% 
  hc_tooltip(formatter = JS("function() { return Math.round(100*Math.exp(this.point.x) , 5)/100 + '<br/>' + this.y; }"))
```

This work for you as a temporary fix/solution?

Regards,

**Comment by drodtp** [comment]
The hack works for me, thanks a lot.
I also changed the the title to enhancement instead of bug.

Regards
