### ISSUE TITLE
highcharter/devscripts/drill-down-ex.R

### ISSUE THREAD

**Issue by howard40116** [jbkunst/highcharter#143]
When exec (drill-down-ex.R) then console 

> hc <- highchart() %>%
+   hc_chart(type = "column") %>%
+   hc_title(text = "Basic drilldown") %>%
+   hc_xAxis(type = "category") %>%
+   hc_legend(enabled = FALSE) %>%
+   hc_plotOptions(
+     series = list(
+       boderWidth = 0,
+       dataLabels = list(enabled = TRUE)
+     )
+   ) %>%
+   hc_add_series_df(
+     data = df,
+     name = "Things",
+     colorByPoint = TRUE
+   )
Error: !is.null(type) is not TRUE 

I can't find an answer to my question
please help me Thx~

**Comment by jwinter6** [comment]
hi,
a first thought that came up in my mind is that you can try to provide the TYPE in hc_add_series_df.
so:
`hc_add_series_df(
data = df,
type = "column",
name = "Things",
colorByPoint = TRUE
) `

**Comment by jbkunst** [comment]
Hi @howard40116 ,

The function `hc_add_series_df`have been reworked and don't follow the structure of the others `hc_add_seres_*etc*` (in fact **this is the only** function which the `...` are using for the data frame instead of using for the series options). 

The alternative is use `hc_add_series` instead of `hc_add_series_df` and change `data = df` by  `data = list_parse(df)`:

```
  hc_add_series(
    data = list_parse(df),
    name = "Things",
    colorByPoint = TRUE
  )
```

Tell me how it goes ;)!

**Comment by howard40116** [comment]
@jbkunst @jwinter6 
Very thanks for  two Stronger's help
It's successfully solve my problems with two solution
THX~

Solution1:
![image](https://cloud.githubusercontent.com/assets/18079605/16882664/cf6c09d6-4af2-11e6-9b2c-2ba0d9415559.png)

Solution2:
![image](https://cloud.githubusercontent.com/assets/18079605/16882646/b8eed9ae-4af2-11e6-83ae-fa0a4cb0b042.png)

**Comment by ctmann** [comment]
Is it possible to drill-down with a stacked column, as:
http://jsfiddle.net/highcharts/s5JqN/
