### ISSUE TITLE
highchart() with one category / one column cuts off category name

### ISSUE THREAD

**Issue by bogdanrau** [jbkunst/highcharter#155]
See reproducible code below. The category name (var1) shows up as v. 

```
test <- data.frame(class = "var1", data = 20)

highchart() %>%
hc_title(text = "title") %>%
hc_legend(enabled = FALSE) %>%
hc_add_series(name = "Service Area", data = test$data, type = "column",
              negativeColor = "red", color = "green") %>%
hc_xAxis(categories = test$class)
```

**Comment by jbkunst** [comment]
Hi @bogdanrau ,

This is a htmlwidgets/jsonlite related. Internally, htmlwidgets default for jsonlite (wich pass the info to html/javascrtipt) is `auto_unbox = TRUE` so intead of pass `categories = ['var1']` use `categories = 'var1'` because `length(test$class)` is 1. So highcharts produce this strange behaviours. You can see more discussion on #65 and #71.

The solutions are:

```
# use
hc_xAxis(categories = list(test$class))
``` 

or

```
# the same code but previous run
options(htmlwidgets.TOJSON_ARGS = list(auto_unbox = FALSE))
```

Regards!

**Comment by bogdanrau** [comment]
Excellent. I ended up using an if else statement dependent on the nrow of my data frame. setting auto_unbox to FALSE ends up messing with other htmlwidget packages I'm using. Thanks for your help @jbkunst!
