### ISSUE TITLE
Question: How I can draw a rectangle on a plot?

### ISSUE THREAD

**Issue by Rhoboot** [jbkunst/highcharter#199]
Highcharts use is that if there is "chart.renderer.rect" function that would draw a rectangle or a specific area within a graphic but can not find how to do it from highcharter.

Here is an example of its use.
http://jsfiddle.net/fEySL/

Is it possible to do this with Highcharter?

**Comment by jbkunst** [comment]
Holas @Rhoboot ,

The function is not `chart.renderer.rect` but `renderer.rect` since the `chart` is the object. You can use the event  `load` to draw the rectangles. In this function the `chart` elements is refereced as `this`, all this in the `JS` functions due is a javascript code, so:

```
library(highcharter)

highchart() %>% 
  hc_add_series(data = rnorm(10), type = "scatter") %>% 
  hc_chart(
    events = list(
      load = JS("
function(event){

  var width = this.plotBox.width / 2.0;
  var height = this.plotBox.height / 2.0 + 1;          

 this.renderer.rect(this.plotBox.x,                      
                            this.plotBox.y, width, height, 1)
                .attr({
                fill: 'lightblue',
                zIndex: 0
                })
                .add();


}        
      ")
    )
  )

```
![image](https://cloud.githubusercontent.com/assets/56481/19227046/60c5c5e0-8e8a-11e6-926e-036113229b54.png)

Hope this help!

**Comment by Rhoboot** [comment]
Excellent!! Thank
