### ISSUE TITLE
Draggable lines don't work anymore in develop version

### ISSUE THREAD

**Issue by tbenschop** [jbkunst/highcharter#227]
I have a customized draggable lines plot where the dragged lines values show up in a table. This works fine just fine in ``highcharter`` version 0.4.0 but in the latest develop version it doesn't. Please find an example on [GitHub](https://github.com/tbenschop/Highcharter/)

**Comment by jbkunst** [comment]
Yep, sorry, this was the same as your previous issue https://github.com/jbkunst/highcharter/issues/28#issuecomment-202808297, because I removed undesrcore __again__ but this time permanently because __is not a dependency__ for highcharter, and only add file size to the package.

Anyway, you can solve adding to ui file something like this:

```r
tags$head(tags$script(src="https://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.8.3/underscore-min.js"))
```

Some references:

- http://stackoverflow.com/questions/23599268/include-a-javascript-file-in-shiny-app
- http://stackoverflow.com/questions/24881931/including-js-css-scripts-in-shiny-app

Test and tell me if this fix the problem. 

Sorry for the inconvenient.

**Comment by tbenschop** [comment]
Thanks @jbkunst. No need to say sorry, you've created a great package!
