### ISSUE TITLE
Adding color legend to column graph

### ISSUE THREAD

**Issue by ProQuestionAsker** [jbkunst/highcharter#230]
Hi there. First of all, I love highcharter!! Thank you so much for this :)

I am currently working on making a column graph where I show the use of different things by category.  I started by making a normal hchart column graph where color = category and I got exactly the figure I was expecting (1 bar per name), but there was no legend!
![screen cap 1](https://cloud.githubusercontent.com/assets/11020849/21404794/b453d24e-c777-11e6-822b-319e7bec5680.PNG)

So I tried group = category thinking it would accomplish something similar, but I was now getting multiple bars per name. 
![screen cap 2](https://cloud.githubusercontent.com/assets/11020849/21404826/d648ea06-c777-11e6-9d0b-3f32b03c6ac8.PNG)

I tried adding each category as a separate series, but since my x-axis is filled with categorical variables, I couldn't get the labels to work correctly with more than one series.  Is there any way to add a legend for column charts with a color = category argument? 

Thanks again!

**Comment by jbkunst** [comment]
Hi @ProQuestionAsker Amber!

Thanks for use the package! and come here with use cases.

Ok, the chart is simple, but highcharts is kind of weird when you want to put un value in a categorical xAxis and having some series.

Try the following:

```r
library(highcharter)
library(dplyr)

n <- 12

set.seed(123)

data <- data_frame(
  value = 1:n + runif(n, 0,.5),
  name = month.abb,
  category = sample(LETTERS[1:3], size = n, replace = TRUE)
)

data

hchart(data, "column", hcaes(name, value, color = category))

hchart(data, "column", hcaes(name, value, group = category))

hchart(data, "column", hcaes(name, value, color = category,
                             group = category))

# Auxiliar variable to force the position (js is 0-index)
data <- mutate(data, position = 1:n - 1)

hc <- hchart(data, "column", hcaes(position, value, group = category))
hc

hc <- hc %>% 
  hc_xAxis(categories = data$name)
hc
```

You will have:

![image](https://cloud.githubusercontent.com/assets/56481/21414768/468b3e68-c7e1-11e6-981f-01bea6cff0a0.png)

If you see, there some offset due the other series dont have values in that category so the chart looks weird because highcarts make the space to the missing values. For example it's clear if you see this jsfiddle: http://jsfiddle.net/d13d3u6t/

![image](https://cloud.githubusercontent.com/assets/56481/21414757/2e52a08e-c7e1-11e6-8590-e9b3a541d76b.png)


Now, using this example http://jsfiddle.net/gh/get/jquery/3.1.1/highslide-software/highcharts.com/tree/master/samples/highcharts/demo/column-placement/  we can set __manually__ the position of the columns for each group/series:

```r
hchart(data, "column", hcaes(position, value, group = category),
       pointPlacement = c(2,0,-2)/10) %>% 
  hc_xAxis(categories = data$name)
```

![image](https://cloud.githubusercontent.com/assets/56481/21414841/159256e2-c7e2-11e6-92ce-e1d121750276.png)

It works :/,  but if you deselect a series the rest of them shows misplaced.

There's another solution: http://jsfiddle.net/zmktekak/14/ but let me try to implement this _pluging_/_fix_ in an easy way.

Sorry if this not that elegant but it's a highcharts treatment.

Finally a really _dirty_ solution is generate the first chart without legends, and then add artificial series with no data, but show this series in the legend:

```r
colors <- colorize(1:3)

hchart(data, "column", hcaes(name, value, color = category)) %>% 
  hc_add_series(data = NULL, name = "As", color = colors[1], showInLegend = TRUE) %>% 
  hc_add_series(data = NULL, name = "Bs", color = colors[2], showInLegend = TRUE) %>% 
  hc_add_series(data = NULL, name = "Cs", color = colors[3], showInLegend = TRUE, type = "scatter") %>% 
  hc_xAxis(categories = data$name)
```

![image](https://cloud.githubusercontent.com/assets/56481/21415097/c3c253b4-c7e4-11e6-81a6-07498a45143c.png)

**Comment by ProQuestionAsker** [comment]
Hi @jbkunst, thank you so much for the quick (and very thorough) response!

I have so many options now!! I'l mess with this in a bit and get back to you with which one ended up working best for my use case.  Thanks again!

**Comment by ProQuestionAsker** [comment]
Hmm @jbkunst, I'm trying to test these options, but I'm getting an error when I try to use hcaes() that reads "Error in eval(expr, envir, enclos) : could not find function "hcaes"". I tried running just the hchart() function with hcaes and still received the error "Error: could not find function "hcaes"".  I tried downloading the latest version of highcharter just in case I was using an old version, but no luck. :( Any thoughts on how to fix that?

**Comment by jbkunst** [comment]
Sorry @ProQuestionAsker! I forgot to tell you I was using the development version (0.5.0) of highcharter, which you can download using `devtools` package. Tell me if you have look with this ;).

**Comment by ProQuestionAsker** [comment]
@jbkunst Sorry for the delay! I ended up just adding the label name to to the tool tip because I couldn't quite get any of those to work the way I needed.  Also, in downloading the development version, I ran into a few other problems:

- When you zoom in on column charts, the x-axis labels stop working. Then, zooming all the way out results in a complete disappearance of the columns you had just zoomed in on. 
- Inability to color by type (adding a `color = "section"` to the hcaes field wouldn't change the colors. 

I reverted back to the version I'd been using and found one more potential issue: 

- When adding color by a categorical variable (i.e. `color = section` like above) that works fine for a limited number of categorical variables.  But you can't change the theme or the colors that are used for each section.  

Let me know if you'd like me to open any of those as separate issues.  Thanks again for everything!

**Comment by jbkunst** [comment]
Hi @ProQuestionAsker!

- Can you give a replicable example? Maybe post something in http://rpubs.com/. I tried with `hc_chart(zoomType = ...)` but the behavior is normal.

- why `color = "section"` and not `color = section`?

- Yes, in the previous version if you use `color = variable` the same color palette is used to color the points/bars not matter what `hc_theme_*` is used, because the function set a color to the point via (`colorize` function `colorize(c(1, 1, 1:10))`). In the development version this was fixed and if the variable used to add color have an hexadecimal patter (a color) those colors will be used so you can use you custom colors.

**Comment by jbkunst** [comment]
I will close this due inactivity ;)! We can reopen the issue if is needed. :B.

**Comment by CRstritt** [comment]
Hey, I am having a bit of an issue running this - receiving error `Error in eval(substitute(expr), envir, enclos) : 
  could not find function "hcaes"` after running `library("gapminder")
library("tidyverse")

library("highcharter")
gapminder %>%
  group_by(continent, year) %>%
  summarise(continent.population = sum(as.numeric(pop))) %>%
  hchart("area",
        hcaes(x = year,
              y = continent.population,
              group = continent)
         ) %>%
  hc_plotOptions(area = list(stacking = "normal")) %>%
  hc_tooltip(shared = TRUE)`

**Comment by meetshah15** [comment]
I want to create a chart consisting of a single column chart whose colors changes when a negative value is inserted. Hence I'm passing colors as a list and enabling colorsByPoint to true for that particular series.
However, I'm unable to decide the legend icon because of that. Can anyone suggest a work around for this?
