### ISSUE TITLE
Coloring one word in title

### ISSUE THREAD

**Issue by mportillo14** [jbkunst/highcharter#234]
I'm having trouble coloring select words in the title.

`hc_title(text = "Annual Growth: <font color="red">Predicted</font> vs <font color="blue">Actual</font>",
                 style = list(fontWeight = "bold", useHTML = TRUE),
                 align = "left")`

I know I can do custom bold `<b>` or italicized words `<i>` in the title, but how would I customize the color for select words in the title? The quotations cause me problems. Any help would be appreciated.

Thanks.

**Comment by jbkunst** [comment]
Hi @mportillo14 

First of all, this type of question if more appropiate for stackoverflow ;).

Secondly, quotation is not really a highcharter issue :P. You need to know how to make quote in a string. You can do it at least in 2 ways:

``` r

"Someone said: 'A quote string'"
#> [1] "Someone said: 'A quote string'"

# or

"Someone said: \"A quote string\""
#> [1] "Someone said: \"A quote string\""
```

Finally the  `useHTML` argument need to be in the `hc_title` as an option instead of `style` argument ;).

Good luck!

**Comment by mportillo14** [comment]
Thank you very much! My apologies about the question. I'll direct these types of questions to stackoverflow in the future.

**Comment by jbkunst** [comment]
@mportillo14 

I'll look every day the [r] and [highcharts] tags ;)! http://stackoverflow.com/search?tab=newest&q=%5br%5d%20highcharts
