### ISSUE TITLE
Plotting xts series with missing values (NA) in Highcharter

### ISSUE THREAD

**Issue by iclarke** [jbkunst/highcharter#253]
Hi there,

First let me congratulate you for the wonderful package Highcharter is, probably the best interactive charting tool around by a large margin. 

My issue involves plotting a multivariate time series where one series contains missing values (NA). When executing the code below RStudio is unable to render a chart, could you point me in the right direction ?

```r
# Loading libraries 

library(highcharter)
library(dplyr)
library(xts)
library(quantmod)

# Creating dummy data frame 

value.q <- c(1,2,3,4,5,6,7)
value.na.q <- c(1,2,3,NA,NA,NA,NA)
date.q <- c("2017-01-01","2017-01-02","2017-01-03","2017-01-04","2017-01-05","2017-01-06","2017-01-07")
df.q <- data.frame(date.q,value.q,value.na.q)
df.q$date.q <- as.Date(df.q$date.q,format = "%Y-%m-%d")


# Converting data frame to xts

df.xts <- xts(df.q[,-1],order.by = df.q$date.q)

# Plotting
hchart(df.xts)
```
Many thanks

Samy

**Comment by jbkunst** [comment]
Hi @iclarke Samy,

It's seem the `hchart` treat your xts object in a wierd way. Usually the (univariate?) xts objects with NA values are treated in the expected way:
``` r
library(highcharter)
library(dplyr)
library(quantmod)

n <- 100
x <- getSymbols("USD/JPY", src = "oanda", auto.assign = FALSE)
x <- tail(x, n)
x[sample(1:n, size = 20)] <- NA

head(x)
#>            USD.JPY
#> 2016-10-23 103.832
#> 2016-10-24      NA
#> 2016-10-25      NA
#> 2016-10-26 104.298
#> 2016-10-27      NA
#> 2016-10-28      NA

hc <- hchart(x)
hc
```
![image](https://cloud.githubusercontent.com/assets/56481/22465796/3c094608-e79c-11e6-8868-fc9cc84f1678.png)

So, I'm not sure why you transform the data to data frame. Anyway, if this is your case, you can do it a kind of manually:

```r
# more explicit way
df <- data_frame(date = as.Date(c("2017-01-01", "2017-01-02", "2017-01-03", 
  "2017-01-04", "2017-01-05", "2017-01-06", "2017-01-07")), value = c(1, 2, 
  3, NA, NA, NA, NA))
df
#> # A tibble: 7 Ã— 2
#>         date value
#>       <date> <dbl>
#> 1 2017-01-01     1
#> 2 2017-01-02     2
#> 3 2017-01-03     3
#> 4 2017-01-04    NA
#> 5 2017-01-05    NA
#> 6 2017-01-06    NA
#> 7 2017-01-07    NA

hc <- highchart(type = "stock") %>%
  hc_add_series(df, "line", hcaes(date, value))
hc
```
![image](https://cloud.githubusercontent.com/assets/56481/22465810/49d16e14-e79c-11e6-9060-88f1ae814334.png)

Tell me if this approach works for you. Otherwise we can work in a more _realistic_ reproducible example ;)!

Best,

**Comment by iclarke** [comment]
Thanks for your quick and detailed reply. By trying to reproduce my error it turns out .. two of my dataframe columns were factors, hence no chart output ! Shame on me on this one. 

I implemented the second solution you suggested and it works perfectly.

Many thanks

Samy
