### ISSUE TITLE
hchart with highchart2 to boost heatmap plotting

### ISSUE THREAD

**Issue by juferban** [jbkunst/highcharter#264]
Hi,

Really love highcharter and have been using it to implement multiple visualizations in a project.
I have now come up with the issue of having to include heatmaps for thousands of data points and I tried using hchart as in the provided example but I find the rendering a bit slow (>30 sec for 10000 data points).
I read in the forums that you have implemented a highchart2 that takes advantage of the boost.js library ([https://github.com/jbkunst/highcharter/issues/160](https://github.com/jbkunst/highcharter/issues/160)).
Is there a way to direct hchart to use highchart2? or to use this function I need to create the plot outside of hchart?

Thanks,

Julio

**Comment by jbkunst** [comment]
Hi @juferban ,

Can you post an example to work with? Just to know how is your approach.

**Comment by juferban** [comment]
Hi, 

Thanks for your quick answer. See code below for a minimal example on how I am currently using highcharter to generate the heatmap. This one took about 15 sec on my desktop which is a bit faster what I am seeing in my real data (which have some additional columns in the dataframe).

I didn't look yet on writing a version that doesn't use the hchart shortcut.

```
a = matrix(rnorm(10000), nrow =100, ncol = 100)
b = melt(a)

hchart(b, "heatmap", hcaes(x = Var1, y = Var2, value = value))
```

Any help would be much appreciated.

Thanks,

Julio

**Comment by jbkunst** [comment]
I think the time it took is to convert the higcharter object -_basically a list_- to __html__ -_the file with (in this case) a big json_-. The higcharter boots pluging improve the performance in tooltip  for example instead of make a fast load of the chart. See http://rpubs.com/jbkunst/highcharter-no-boost versus http://rpubs.com/jbkunst/highcharter-boost they load same time but the performance in zoom and tooltips are different, that is the improvement due to the pluging.

So, if my guess is correct, how you could send less data to html?

If you look the object sended via:

```r
hchart(b, "heatmap", hcaes(x = Var1, y = Var2, value = value))
```
is like 
```
...
{"Var1":12,"Var2":1,"value":0.283813910356557,"x":12,"y":1},
{"Var1":13,"Var2":1,"value":-0.948575281626216,"x":13,"y":1},
{"Var1":14,"Var2":1,"value":-1.38292375427927,"x":14,"y":1},
...
```

Because highcharts send the original data to be used as tooltips for example. So, now if you do:
```
names(b) <- c("x", "y", "value")
b$value <- round(b$value, 4)
hchart(b, "heatmap", hcaes(x, y, value = value))
```

You will send data as:

```
...
{"x":80,"y":1,"value":0.4501},
{"x":81,"y":1,"value":-0.2648},
{"x":82,"y":1,"value":1.0007}
...
```

So the transform the list to html file will be faster. Please, test and tell me how it goes ;)!

**Comment by juferban** [comment]
Hi,

Thanks a lot for the great tip. I tested your suggestion and it cut the time in half. In my real case I was doing the rounding in the javascript for the tooltip as didn't thought about the size of the HTML file so great pointer.

Thanks for the quick answer.

Julio
