### ISSUE TITLE
Vignette not showing up for users who download from GitHub

### ISSUE THREAD

**Issue by smach** [jbkunst/highcharter#44]
I see that you've got a nice vignette file here on GitHub. However, when I download this package using `devtools::install_github("jbkunst/highcharter", build_vignettes = TRUE)` your vignette isn't there when I run `help(package="highcharter")`. 

I've had a similar problem with my own packages at times. I was able to fix this by doing `build(vignettes = TRUE)` locally before pushing a commit to GitHub. I was told that if you just use the RStudio build menu command, vignettes to not get built by default (that's to save time during local development)

**Comment by jbkunst** [comment]
Hi Sharon,

I removed the vignette in the `DESCRIPTION` file (so, the folder exist but is not considerated) because I have some check issues (notes and warnings) when include the vignette and I didnt know the reason. Let me check again and I will message back if I have any news ;)!

Thanks for test the package :smile:

**Comment by smach** [comment]
I like Highcharts and have been looking for a good html widgets version, thanks for the package! I am trying it out on some local Shiny apps and R Markdown documents.

**Comment by jbkunst** [comment]
Sharon,

I updated the package. Can you try `devtools::install_github("jbkunst/highcharter", build_vignettes = TRUE)`? Thanks!

**Comment by smach** [comment]
Vignette is there now, thanks!!
