### ISSUE TITLE
Synchronised plots

### ISSUE THREAD

**Issue by royfrancis** [jbkunst/highcharter#465]
Is it possible to create synchronised plots in highcharter? If yes, would you have an example?

https://www.highcharts.com/demo/synchronized-charts

**Comment by patarol** [comment]
I thik it is possible.

Take a look at [this](https://github.com/jbkunst/highcharter/blob/11f991a53bd0db2d824596d7969ac0bc23e26bd3/dev/stackoverflow/41533909.R).

**Comment by royfrancis** [comment]
This is neat! What does the `yAxis = c(0, 1)` do? Is it possible to change the y-axis titles for each subplot?

**Comment by patarol** [comment]
`yAxis = c(0 ,1)` is needed in order to sort both charts. You can play with the values and see what changes. Also take a look at the `highcharts` [synchronized](https://www.highcharts.com/demo/synchronized-charts/dark-unica) documentation and its jsfiddle charts [example](https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/demo/synchronized-charts/)!

I think it's possible since in the example above they have different title. I have no idea though.

**Comment by jbkunst** [comment]
Hi,

Thanks @patarol  for you support 😅 

@royfrancis  `yAxis = c(0 ,1) ` is needed because if you dont, all your series will be shown in the first axisx  (0 default, js is 0-index), so we are saying 1st series in the axis 0 (the first one) and the second one in the axis 1 (the #2).

**Comment by patarol** [comment]
Thank you @jbkunst for this amazing package!
