### ISSUE TITLE
`hw_grid` argument `ncol` does not affect output

### ISSUE THREAD

**Issue by xinye1** [jbkunst/highcharter#494]
With the dev version (0.6) the output is always 1 column, `ncol` does not seem to affect the output if set to anything greater than 1

**Comment by MaelTheuliere** [comment]
Hello.
Same for me. 
Exemple : 
`ui <- fluidPage(htmlOutput('hchart'))

server <- function(input,output,session){
  
  output$hchart <- renderUI({
    
    map(names(diamonds), function(x){
      diamonds[[x]] %>% 
        hchart(showInLegend = FALSE) %>% 
        hc_add_theme(hc_theme_smpl()) %>% 
        hc_title(text = x) %>% 
        hc_yAxis(title = list(text = ""))
    }) %>% 
      hw_grid(rowheight = 225, ncol = 3) 
    
  })
}

shinyApp(ui=ui,server=server)`

**Comment by jbkunst** [comment]
Hi @xinye1 @MaelTheuliere 

Can you test again with the new development version 0.7.0?

**Comment by MaelTheuliere** [comment]
It's works! 
Thanks!

**Comment by Jolien-GGD** [comment]
First of all, thanks for a great package. :)

I found this old issue while Googling for a solution to my problem. I'm able to create subplots using hw_grid, and in the R Viewer it works fine, but when hosted on a server or when I switch to "Open in Browser" I run into problems. I used the minimal example that MaelTheuliere posted on 11 Jan 2019. I get 3 plots per rows, but each plot seems to have the maximal width. The second and third column are plotted on top of the first column, with the appropriate offset. Because of this you cannot see the entire x-axis on any of the plots (subplot "cut", for example, only shows categories "Fair" and "Good", and misses "Very Good", "Premium" and "Ideal".

![image](https://user-images.githubusercontent.com/50368629/113861918-0e96dd00-97a8-11eb-81db-1c3602163a91.png)

I'm using R version 4.0.2, highcharter version 0.8.2 and my Chrome version is 89.0.4389.114.
