### ISSUE TITLE
Drilldown option in maps with R.

### ISSUE THREAD

**Issue by makis23** [jbkunst/highcharter#507]
Hi I have the dataframe below:

```
State<-c("Alabama","Alabama","Alaska","Alaska")
StateCode<-c("AL","AL","AK","AK")
County<-c("AUTAUGA","BALDWIN","ANCHORAGE","BETHEL")
CountyCode<-c("AL001","AL003","AK020","AK050")
Murder<-c(5,6,7,8)
d<-data.frame(State,StateCode,County,CountyCode, Num)
```
My goal is to create a State-County drill-down map like this [map`](https://www.highcharts.com/maps/demo/map-drilldown) After finding the summary of `Murder `from every State I created a dataframe like the one below:
```
data("USArrests", package = "datasets")
USArrests <- add_rownames(USArrests, "state")
```
(I use USArrests because it is like my orginal dataset in its form in order to use it as example)

Then I use this highcharter github method in order to create the drilldown map:

```
library("highcharter")
library("purrr")
library("dplyr")
library("viridisLite")

data("USArrests", package = "datasets")
data("usgeojson")
data("uscountygeojson")

names(usgeojson)
names(usgeojson$features[[1]])

usgeojson$features <- usgeojson$features %>% 
  map(function(x){
    x$properties$code <- gsub("us-", "", x$properties$code)
    x$properties$name <- x$properties$woename
    x$drilldown <- x$properties[["code"]]
    x$value <- ceiling(abs(rnorm(1)*2))
    x$properties$value <- x$value

    x
  })

names(usgeojson$features[[1]])

names(usgeojson$features[[1]]$properties)
usgeojson$features[[1]]$properties

USArrests <- add_rownames(USArrests, "state")

fn <- JS("function(e){  if (!e.seriesOptions) {  alert(e.point.drilldown) } }")
fn2 <- JS("function () { this.setTitle(null, { text: 'USA' });  }")

highchart(type = "map") %>%
  hc_chart(
    events = list(
      drilldown = fn,
      drillup = fn2
      )
    ) %>% 
  hc_colorAxis(min = 0, minColor = "#FAFAFA", maxColor = "#2D2D2D") %>% 
  hc_series(
    list(
      data = USArrests %>% select(name = state, value = Murder) %>% list_parse(),
      mapData = usgeojson,
      joinBy = "name",
      # data = usgeojson,
      # type = "map",
      name = "USA",
      dataLabels = list(
        enabled = TRUE,
        format = "{point.properties.code}"
      )
    )
  ) %>% 
  hc_drilldown(
    activeDataLabelStyle = list(
      color = '#FFFFFF',
      textDecoration = 'none',
      textShadow = '0 0 3px #000000'
    ),
    drillUpButton = list(
      relativeTo =  'spacingBox',
      position = list(x = 0, y = 60)
    )
  ) 
```
The state map may be created but there is no drill down ability and my assumption is because there is no connection between my initial dataframe with the county-level data with the new one. Does anybody know how to make it work?

**Comment by NahuelBargas** [comment]
Hi, I've adapted a little bit the documentation on this page:
https://rdrr.io/github/jbkunst/highcharter/src/dev/sandbox/map-drilldown.R 
in order to reproduce your example.

# Drilldown with USArrests


library(dplyr)
library(tidyr)
library(htmltools)
library(highcharter)


## Prepare the Databases

data("USArrests", package = "datasets")
USArrests <- add_rownames(USArrests, "State")


USArrests<- USArrests %>% mutate( state_po = c ("AL", "AK", "AZ", "AR", "CA","CO", 
"CT","DE","FL","GA","HI","ID","IL","IN","IA","KS","KY","LA","ME", "MD", "MA", "MI", 
 "MN","MS", "MO", "MT", "NE", "NV", "NH", "NJ", "NM", "NY", "NC", "ND", "OH", "OK", "OR", "PA", 
"RI", "SC", "SD", "TN","TX", "UT", "VT", "VA", "WA", "WV", "WI", "WY"))

USArrests$state_po<-as.factor(USArrests$state_po)
USArrests$State<-as.factor(USArrests$State)


USArrests<- USArrests %>% mutate( state_fips = c (1, 2,  4,  5,  6,  8,  9, 10,
12, 13, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 44, 45, 46, 47, 48, 49, 50, 51, 53, 54, 
55, 56))


USArrests.cn<-tibble(State_Name=c("Alabama","Alabama","Alaska","Alaska"),
state_po= factor(c("AL","AL","AK","AK")),
CountyName= factor(c("Autawa","Baldwin","Anchorage","Bethel")),
FIPS= c("01001","01003","02020","02050"),
StFIPS= c(1,1,2,2),
Murder= c(5,6,7,8))


data("usgeojson") 
data("uscountygeojson")


##Create Data for Mapping & Tooltips


#create index vector to subset uscountygeojson by state code
cn_st_index <- unlist(lapply(uscountygeojson$features, function (x){
  if(is.null(x$id))
    NA
  else
    str_to_lower(x$properties$fips) %>% str_sub(1, 2) %>% as.numeric()
}))

build_series <- function(stateCode) {
  
  #subset uscountygeojson
  uscountygeojson.subset <- uscountygeojson
  uscountygeojson.subset$features <- uscountygeojson$features[which(cn_st_index == stateCode)]
  
  #subset county data
  usa.cn <- filter(USArrests.cn, StFIPS == stateCode) %>% 
    transmute( code = FIPS, value = Murder, cnlabel = CountyName, stlabel = State_Name) %>%
    list_parse()
  
  #build series
  list(
    id = stateCode,
    mapData = uscountygeojson.subset,
    data = usa.cn,
    joinBy = c('fips',"code"),
    dataLabels = list(enabled = TRUE, format = '{point.name}'),
    tooltip = list(
      useHTML = TRUE,
      headerFormat = "<p>",
      pointFormat = paste0("<b>{point.stlabel}, {point.cnlabel}</b><br>",
                           "<b style=\"color:#1874CD\"> Murder arrests:</b> {point.value:.1f}<br>"),
      footerFormat = "</p>")
  )
}



  
#leave only necessary variables from state df

usa.ts<- USArrests %>% 
    transmute(code = state_fips, value= Murder,stlabel = State, drilldown = state_fips)
usa.st<- list_parse(usa.ts)
  
#create drilldown series

series.list <- lapply(usa.ts$drilldown, build_series)
  
#tooltim for state map has to be coded separately from tooltip for county
  
usamap<- highchart(type = 'map') %>%
    hc_add_series(
      mapData = usgeojson, data = usa.st, joinBy = c("statefips", "code"),
      borderWidth = 0.8, dataLabels = list(enabled = TRUE, format = '{point.properties.postalcode}'),
      tooltip = list( 
        useHTML = TRUE,
        headerFormat = "<p>",
        pointFormat = paste0("<b>{point.stlabel}, {point.cnlabel}</b><br>",
                           "<b style=\"color:#1874CD\"> Murder arrests:</b> {point.value:.1f}<br>"),
        footerFormat = "</p>"
      )) %>%
    hc_plotOptions(map = list(states = list(hover = list(color = '#FFFFFF')))) %>%
    hc_colorAxis(min = 0, minColor = "#FAFAFA", maxColor = "#2D2D2D") %>% 
    hc_title(text = "Murder arrests (per 100,000) -- 1973") %>%
    hc_legend(enabled = TRUE) %>%
    hc_exporting(enabled = TRUE)%>%
    hc_drilldown(
      series = series.list,
      activeDataLabelStyle = list(
        color =  '#FFFFFF',
        textDecoration = 'none'
      )
    ) 



usamap %>% save_html(file = 'outputUSAMap.html')




Now, you can test the drilldown for Alaska and Alabama states.

I hope that it will be useful for everyone who has your same doubt.

Thanks to jbkunst for his massive work.

Best 
Nahuel
