### ISSUE TITLE
Outliers of boxplot always appear in the middle even with many series

### ISSUE THREAD

**Issue by stelmath** [jbkunst/highcharter#519]
Hello, please have a look at the image below. 
![asdads](https://user-images.githubusercontent.com/38814495/55326638-e7a6c180-5490-11e9-9c3a-a03dc4e7ba55.PNG)
this isn't normal, right? I am using `hc_add_series_boxplot` to build this. 
Also, what is the argument that changes the "v" on the bottom of the plot to something more intuitive?
Thanks.

**Comment by jbkunst** [comment]
Yeah, this clearly a bug, it is seams at least 😅 

Can you give me a reproducible example please to work with?

Thanks!

**Comment by stelmath** [comment]
Sorry for the delay,

You can play around with this:

```
library(shiny)
library(highcharter)
library(dplyr)

shinyApp(
  ui <- fluidPage(
    fluidRow(highchartOutput("test"))
  ),
  server = function(input, output) {
    
    output$test <- renderHighchart({
      x <- c(-40,1,2,3,4,5,6,7,9,10,11,20,51,66)
      y <- c(1,2,3,4,5,6,7,9,10,11,20,121)
      
      list_of_series <- list(x,y)
      hc <- highchart() 
      
      for (dataseries in list_of_series) {
        hc <- hc %>% hc_add_series_boxplot(x = dataseries,  outliers = TRUE)
      }
      hc
    })
  }
)
```
I know there are other more simple ways that might work, but in my real code that I have for my company, I really need to use a loop and use something like `hc <- hc %>% hc_add_series_boxplot(x = dataseries,  outliers = TRUE)`

However, on my machine, when I run this I do not even see the outliers on the plot. Only in the Legend. Like this:
![Capture](https://user-images.githubusercontent.com/38814495/55629596-3b304c80-57bc-11e9-9615-8cfe94da2320.PNG)

**Comment by stelmath** [comment]
@jbkunst kind reminder

**Comment by ttzhou** [comment]
> Yeah, this clearly a bug, it is seams at least sweat_smile
> 
> Can you give me a reproducible example please to work with?
> 
> Thanks!

Reprex code below:

```r
highchart() %>%
  hc_add_series_list(
    ToothGrowth %>%
    dplyr::mutate(supp = as.character(supp)) %>%
    dplyr::mutate(dose = as.character(dose)) %>%
    data_to_boxplot(
      len,
      dose,
      supp,
      add_outliers = T
    )
  )
```

The output will show the outlier floating between two boxplots placed at the x-axis of "1".

In general, this problem is also not easily solved on the JS side - the scatter is a separate series, and it's x-position has to be calculated depending on the number of groups to get it to be positioned correctly. If you specify it manually, it will be incorrect if you hide one or more of the series, as the point is fixed in position.

The only method I can think of to do this dynamically and robustly is via a callback on `event`; see [here](https://stackoverflow.com/questions/42224403/highcharts-how-to-plot-adjacent-scatter-points-for-different-box-plots) for some ideas.

**Comment by stelmath** [comment]
@ttzhou wow I had forgotten about this issue. Well, don't bother fixing it now. Is jbkunst alright by the way?

**Comment by jbkunst** [comment]
Hi @stelmath @ttzhou 

Yes, as @ttzhou said is a highchartsJS side issue.  https://github.com/jbkunst/highcharter/issues/519#issuecomment-665419939

Here more discussion/ideas https://www.highcharts.com/forum/viewtopic.php?t=37803
