### ISSUE TITLE
N=45 is the limit for rendering node labels

### ISSUE THREAD

**Issue by pachamaltese** [jbkunst/highcharter#586]
this example works for any N<=45, for larger values the nodes become painted black and no label is shown.

```r
library(igraph)
library(highcharter)

N <- 46

net <- sample_gnp(N, p = 2/N)
wc <- cluster_walktrap(net)

V(net)$label <- seq(N)
V(net)$name <- paste("I'm #", seq(N))
V(net)$page_rank <- round(page.rank(net)$vector, 2)
V(net)$betweenness <- round(betweenness(net), 2)
V(net)$degree <- degree(net)
V(net)$size <- V(net)$degree
V(net)$comm <- membership(wc)
V(net)$color <- colorize(membership(wc))

hchart(net, layout = layout_with_fr)
```

**Comment by nteetor** [comment]
I couldn't reproduce the problem, however it sounds very similar to one I've encountered in the past. If the problem is persisting, try disabling the highcharts boost feature, `<chart> %>% hc_boost(enabled = FALSE)`. This feature is enabled by default.

**Comment by uvedhe** [comment]
Had a similar problem with adding lots of series to a bubble chart. The cut-off turned out to be 50. See post here: https://stackoverflow.com/questions/61269787/highcharts-highcharter-ignores-point-color-when-plotting-50-series/61323815#61323815.

Adding `%>% hc_boost(enabled = FALSE)` solved the problem!

**Comment by jbkunst** [comment]
Since highcharter 0.8.2 boost module is disabled by deafult!
