### ISSUE TITLE
New CRAN release incorporating HighCharts version 8?

### ISSUE THREAD

**Issue by AlexPars** [jbkunst/highcharter#605]
What is the timeline for a new CRAN release incorporating HighCharts version 8?

Highcharter is a great package, BTW

**Comment by rwaaijman** [comment]
Also I'm very interested. At our company we are only allowed to work with CRAN... and there are very interesting features in HighCharts version 8

**Comment by jbkunst** [comment]
{highcharter} uses now version 8.2! 

Thanks.

**Comment by rwaaijman** [comment]
Great!!!Many many many thanks for all your workRoelof
-------- Oorspronkelijk bericht --------Van: Joshua Kunst <notifications@github.com> Datum: 31-07-20  07:33  (GMT+01:00) Aan: jbkunst/highcharter <highcharter@noreply.github.com> Cc: rwaaijman <r.waaijman@gmail.com>, Comment <comment@noreply.github.com> Onderwerp: Re: [jbkunst/highcharter] New CRAN release incorporating HighCharts version 8? (#605) 
{highcharter} uses now version 8.2!
Thanks.

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/jbkunst/highcharter/issues/605#issuecomment-666932827",
"url": "https://github.com/jbkunst/highcharter/issues/605#issuecomment-666932827",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by AlexPars** [comment]
Great news. Thank you
