### ISSUE TITLE
odd behavior on version 0.8.2 with stock charts

### ISSUE THREAD

**Issue by zac-garland** [jbkunst/highcharter#662]
I've noticed some odd behavior with the new version of highcharter for stock charts.  

From the code below, you'll notice that the close is held at 30 which is the value of a lower level for a RSI dual axis chart. 

Does this chart type use position match for columns rather than defined names? Any other ideas on what might be occurring here?

``` r
# packages
pacman::p_load(tidyquant,highcharter,tidyverse)

packageVersion("highcharter")
#> [1] '0.8.2'


# stock data
ind_df <- tq_get("AAPL") %>%
  tq_mutate(
    select = adjusted, 
    mutate_fun = RSI,
    n = 14
  ) %>%
  mutate(
    lower_level = 30,
    upper_level = 70
  )

# to xts
ind_xts <- xts(ind_df[, !(colnames(ind_df) %in% c("symbol", "date"))], ind_df$date)

# chart
highchart(type = "stock") %>%
  hc_add_series(ind_xts, yAxis = 0, name = "AAPL")
```

![](https://i.imgur.com/rkXIa0I.png)

<sup>Created on 2020-08-28 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by jbkunst** [comment]
Hi @zac-garland 

First of all, are you sure this is related only with the recent version of highcharter? I don't think so.

Now, according with my debug this is related to your `ind_xts` is ohlc data accorgin to `quantmod::OHLC` function, then internally `quantmod::OHLC(ind_xts)` don't extract the correct columns. See reprex.

I guess the `quantmod::OHLC` makes partial matching and extract the *lower*_level  and strange things happen. If you remove the levels columns the charts works fine.

In this case, as you use `tidyquant` (tidy-data) you can chart data frames instead of `xts` so you can have more control over the outputs, ie,  `hc_add_series(ind_df, type = ..., hchaes(x = ...)` etc.

Hope this help. Remember close the issue is this solve your problem.

``` r
suppressPackageStartupMessages({
  library(highcharter)
  library(tidyquant)
  library(dplyr)    
})

# stock data
ind_df <- tq_get("AAPL") %>%
  tq_mutate(
    select = adjusted, 
    mutate_fun = RSI,
    n = 14
  ) %>%
  mutate(
    lower_level = 30,
    upper_level = 70
  )

# to xts
ind_xts <- xts(ind_df[, !(colnames(ind_df) %in% c("symbol", "date"))], ind_df$date)

quantmod::is.OHLC(ind_xts)
#> [1] TRUE

head(quantmod::OHLC(ind_xts))
#>                open     high      low lower_level    close
#> 2010-01-04 30.49000 30.64286 30.34000          30 30.57286
#> 2010-01-05 30.65714 30.79857 30.46429          30 30.62571
#> 2010-01-06 30.62571 30.74714 30.10714          30 30.13857
#> 2010-01-07 30.25000 30.28571 29.86429          30 30.08286
#> 2010-01-08 30.04286 30.28571 29.86572          30 30.28286
#> 2010-01-11 30.40000 30.42857 29.77857          30 30.01572
```

<sup>Created on 2020-08-28 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by zac-garland** [comment]
@jbkunst that makes sense. So the underlying problem is with `quantmod::OHLC`. 

Behind the scenes, does highcharter not use column names in the `highchart(type="stock")` defaults? 

i.e.

```
highchart(type = "stock") %>%
  hc_add_series(data = ind_df,type = "candlestick",
    hcaes(
    x = date,
    open = open,
    high = high,
    low = low,
    close = close
  ))

```

If not, that's all good and I can close, but I would've thought that highcharter would column match by name.

**Comment by jbkunst** [comment]
Yes, the `hcaes` just rename internally the columns so you can do:

```r
highchart(type = "stock") %>%
  hc_add_series(data = ind_df,type = "candlestick", hcaes(x = date))
```

**Comment by zac-garland** [comment]
got it that's an easy fix. Thanks for your time and looking into it!
