### ISSUE TITLE
implement hc_add_series_bwp for box and whisker plots

### ISSUE THREAD

**Issue by dkilfoyle** [jbkunst/highcharter#81]
Unlike plotly, highcharts `hc_chart(type="boxplot")` needs to be fed series with the calculated box and whisker values, not just the raw data numbers. 

See mockup for a simple solution below. This works but has no error checking.

```r
hc_add_series_bwp = function(hc, value, by, ...) {
  z=lapply(levels(by), function(x) {
    boxplot.stats(value[by==x])$stats
  })
  
  hc %>%
    hc_xAxis(categories=levels(by)) %>% 
    hc_add_series(data=z, ...)
}

hc_add_series_bwpout = function(hc, value, by, ...) {
  z = lapply(levels(by), function(x) {
    bpstats = boxplot.stats(value[by == x])$stats
    outliers = c()
    for (y in na.exclude(value[by == x])) {
      if ((y < bpstats[1]) | (y > bpstats[5]))
        outliers = c(outliers, list(which(levels(by)==x)-1, y))
    }
    outliers
  })
  hc %>%
    hc_add_series(data = z, type="scatter", ...)
}

highchart() %>% 
  hc_chart(type="boxplot") %>% 
  hc_add_series_bwp(value=iris$Sepal.Length, by=iris$Species) %>% 
  hc_add_series_bwpout(value=iris$Sepal.Length, by=iris$Species) %>% 
  hc_legend(enabled=F)
```

Separate add_series for the box/whisker and outliers allows you to style each separately.

Thanks for the excellent package!

**Comment by jbkunst** [comment]
Whoa! :D Thanks so much @dkilfoyle !

I forgot the boxplot! I modified little your implementation:

http://rpubs.com/jbkunst/hc_add_series_boxplot

1. I used the hadleyverse packages because I'm a fan!
1. Add argument `outliers` to show or not the outliers *given* by the  `boxplot.stats` function. So no extra function. I think about the separated functions for the styles but I it can be managed using `hc_plotOptions` (see link)
1. In the function add the `type = 'boxplot'` argument to avoid use `hc_chart`

I think the function need more detail for show better labels in the outliers but this is a good start. Thanks.

Finally, If you dont mind, can you give me some time to put you as ctb for this function?

Thanks again.

**Comment by dkilfoyle** [comment]
Hi Joshua. Thanks for incorporating this - your version is much better. Silly me for not noticing that boxplot.stats already has the outliers computed. May I suggest a further two tweaks to your version. Here is an [example](http://rpubs.com/dkilfoyle/175420) incorporating the following:

1. Added `linkedTo` option to outlier series so that the outliers don't show up as a separate entry in the legend and toggling the series on/off includes both the boxplot and the outliers.
2. Changed outlier tooltip so that it doesn't reference numeric X axis values.

Thanks again for a wonderful project. Sorry to duplicate comment - I'm still bit of a git-noob. Added as comment to your commit but perhaps better here for reference. 

Dean Kilfoyle

**Comment by jbkunst** [comment]
Done it
